---
- hosts: "{{ hosts }}"
  remote_user: root 
  roles:
    - { role: replica, when: mysql_roles  == "replica" }
    - { role: test, when: mysql_roles == "test" }
    - { role: mgr, when: mysql_roles == "mgr" }
